AllCops:
  Include:
    - '**/Rakefile'
    - '*gemspec'
    - '**/*.rb'

Style/GuardClause:
  Enabled: false

Style/FileName:
  Enabled: false

Style/LineLength:
  Max: 100

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/ClassLength:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Alias:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
